server:
  port: 8081
  servlet:
    context-path: /luckymoney

limit:
  minMoney: 0.01
  maxMoney: 9999
  description: You must give at least ${limit.minMoney} dollars and at most ${limit.maxMoney} dollars

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/luckymoney?characterEncoding=utf-8
    username: root
    password: chenyue612
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
