server:
  port: 8081
  servlet:
    context-path: /luckymoney

Limit:
  minMoney: 1
  maxMoney: 9999
  description: You must give at least ${Limit.minMoney} dollars and at most ${Limit.maxMoney} dollars